image:
  repository: mrballcb/turnserver
  tag: latest
  imagePullPolicy: IfNotPresent
replicas: 1
env:
- name: TURN_USER
  value: root
- name: TURN_PASS
  value: root
- name: TURN_REALM
  value: root
#- name: TURN_ARGS
#  value: --prod --no-cli
persistence:
  enabled: false
service:
  type: LoadBalancer
  protocol: TCP
  port: 443
  containerPort: 3478
  elbCertficateArn: arn:aws:acm:REGION:AWS_ACCOUNT_ID:certificate/CERT_HASH
  baseDomain: foo.example.com
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

