apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    {{- include "default_selector" . | indent 4 }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    dns: route53
    heritage: {{ .Release.Service }}
{{- if eq .Values.service.type "LoadBalancer" }}
{{- if .Values.service.elbCertificateArn }}
  # Annotation docs for AWS ELB controls:
  # - https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L72
  annotations:
    # Enables Proxy Protocol Version 1, requires haproxy ingress to properly use, proxy-kube not supports yet
    #service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: *
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.service.elbCertficateArn }}
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
{{- if ne .Values.uniqueStackId "prod" }}
    external-dns.alpha.kubernetes.io/hostname: turn-{{ .Values.uniqueStackId }}.{{ .Values.service.baseDomain }}.
{{- end }}
{{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: turn-tls
    port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol | upper }}
    targetPort: {{ .Values.service.containerPort }}
  selector:
    {{- include "default_selector" . | indent 4 }}
